#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Juicer - Administer Pulp and Release Carts
# Copyright © 2012, Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

from juicer.tests.TestJuicer import TestJuicer
from juicer.tests.TestJuicerAdmin import TestJuicerAdmin
import unittest

def main():
    suite = unittest.TestSuite()
    suite.addTest(unittest.TestLoader().loadTestsFromTestCase(TestJuicer))
    suite.addTest(unittest.TestLoader().loadTestsFromTestCase(TestJuicerAdmin))
    unittest.TextTestRunner(verbosity=2).run(suite)

if __name__ == '__main__':
    main()
