'\" t
.\"     Title: juicer.conf
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 07/21/2012
.\"    Manual: Pulp repos and release carts
.\"    Source: Juicer 0.1.9
.\"  Language: English
.\"
.TH "JUICER\&.CONF" "5" "07/21/2012" "Juicer 0\&.1\&.9" "Pulp repos and release carts"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
juicer.conf \- juicer configuration file
.SH "DESCRIPTION"
.sp
Sections and variables to use in your juicer configuration file\&. This file is broken into 2 or more parts\&. The first is \fBDEFAULT\fR and the rest are named after your environments, e\&.g\&., \fIqa\fR, \fIstage\fR, or \fIprod\fR\&.
.sp
Assuming you have \fIqa\fR, \fIstage\fR, and \fIprod\fR, environments, you might have a configuration file that looks like this:
.sp
.if n \{\
.RS 4
.\}
.nf
[base]
username: packager
password: s7r0ngP@55
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
[re]
base_url: https://pulp\&.util\&.phx1\&.redhat\&.com/re/pulp/api
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
[qa]
base_url: https://pulp\&.util\&.phx1\&.redhat\&.com/qa/pulp/api
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
[stage]
base_url: https://pulp\&.util\&.phx2\&.redhat\&.com/stage/pulp/api
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
[prod]
base_url: https://pulp\&.util\&.phx2\&.redhat\&.com/stage/prod/api
.fi
.if n \{\
.RE
.\}
.SH "FILES"
.sp
\fB~/\&.juicer\&.conf\fR \(em Juicer configuration file
.SH "AUTHOR"
.sp
Juicer was written by GCA\-PC, Red Hat, Inc\&.\&. This man page was written by Tim Bielawa <tbielawa@redhat\&.com>\&.
.SH "COPYRIGHT"
.sp
Copyright \(co 2012, Red Hat, Inc\&.\&.
.sp
Juicer is released under the terms of the GPLv3+ License\&.
.SH "SEE ALSO"
.sp
\fBjuicer\fR(1), \fBjuicer\-admin\fR(1)
.sp
The Juicer Homepage: http://github\&.com/abutcher/juicer/
