'\" t
.\"     Title: juicer-admin
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/10/2013
.\"    Manual: Pulp repos and release carts
.\"    Source: Juicer 0.6.0
.\"  Language: English
.\"
.TH "JUICER\-ADMIN" "1" "10/10/2013" "Juicer 0\&.6\&.0" "Pulp repos and release carts"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
juicer-admin \- manage pulp repositories, users, and roles\&.
.SH "SYNOPSIS"
.sp
juicer\-admin [\-vvv] [\-V] subcommand [PARAMETERS \&...] [OPTIONS \&...] [\-\-in env \&...]
.SH "DESCRIPTION"
.sp
Manage pulp repositories, users, and roles\&.
.SH "COMMON OPTIONS"
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Increase the verbosity (up to 3x)\&. In usage specify
\fI\-v\fR\fBbefore\fR\fISUBCOMMAND\fR\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Print the version that you\(cqre using of juicer\-admin\&.
.RE
.PP
\fB\-\-in\fR \fIenv\fR \&...
.RS 4
Specify which environment(s) to perform the
\fISUBCOMMAND\fR
in\&. In usage all
\fISUBCOMMAND\fRs accept this option when given after
\fISUBCOMMAND\fR\&.
.RE
.SH "CREATE-REPO"
.sp
usage: juicer\-admin create\-repo REPONAME \-\-arch ARCH \-\-feed FEED
.PP
\fBREPONAME\fR
.RS 4
The name of the repository to be created
.RE
.PP
\fB\-\-arch=\fR\fIARCH\fR
.RS 4
Repository package architecture
.RE
.PP
\fB\-\-feed=\fR\fIFEED\fR
.RS 4
A feed url from which to synchronize yum repository packages
.RE
.PP
\fB\-\-checksum\-type=\fR\fICHECKSUM_TYPE\fR
.RS 4
The checksum type to use when generating meta\-data\&. Defaults to sha256\&.
.RE
.SH "CREATE-USER"
.sp
usage: juicer\-admin create\-user LOGIN \-\-name FULLNAME \-\-password PASSWORD
.sp
Create a user in the pulp system\&.
.PP
\fBLOGIN\fR
.RS 4
Login or username
.RE
.PP
\fB\-\-name=\fR\fIFULLNAME\fR
.RS 4
User\(cqs full name
.RE
.PP
\fB\-\-password=\fR\fIPASSWORD\fR
.RS 4
Plain text password\&. Will prompt if no arg specified
.RE
.SH "DELETE-REPO"
.sp
usage: juicer\-admin delete\-repo \fIREPONAME\fR
.PP
\fBREPONAME\fR
.RS 4
Name of repository which will be deleted
.RE
.SH "DELETE-USER"
.sp
usage: juicer\-admin delete\-user \fILOGIN\fR
.PP
\fBLOGIN\fR
.RS 4
The login or username of user which will be deleted
.RE
.SH "LIST-REPOS"
.sp
usage: juicer\-admin list\-repos
.SH "LIST-ROLES"
.sp
usage: juicer\-admin list\-roles
.sp
See the Pulp User documentation (\fBSEE ALSO\fR) for more information on the specifics of role management\&.
.SH "LIST-USERS"
.sp
usage: juicer\-admin list\-users
.SH "ROLE-ADD"
.sp
usage: juicer\-admin role\-add \-\-role \fIROLE\fR \-\-login \fILOGIN\fR
.PP
\fB\-\-role=\fR\fIROLE\fR
.RS 4
The role which will be assigned to login or username
.RE
.PP
\fB\-\-login=\fR\fILOGIN\fR
.RS 4
Login or username of user which will be added to role
.RE
.sp
See the Pulp User documentation (\fBSEE ALSO\fR) for more information on the specifics of role management\&.
.SH "SHOW-REPO"
.sp
usage: juicer\-admin show\-repo \fIREPONAME\fR
.sp
Show basic statistics about a repo in pulp\&. Currently this command just prints the number of packages in the specified repository\&.
.PP
\fBREPONAME\fR
.RS 4
Name of the repository to show
.RE
.SH "SHOW-USER"
.sp
usage: juicer\-admin show\-user \fILOGIN\fR
.PP
\fBLOGIN\fR
.RS 4
The login for the user to show
.RE
.SH "SYNC-REPO"
.sp
usage: juicer\-admin sync\-repo \fINAME\fR
.PP
\fBNAME\fR
.RS 4
Name of repository to sync
.RE
.SH "UPDATE-USER"
.sp
usage: juicer\-admin update\-user LOGIN \-\-name FULLNAME \-\-password PASSWORD
.sp
Update the
.PP
\fBLOGIN\fR
.RS 4
Login or username of user which will be updated
.RE
.PP
\fB\-\-name=\fR\fIFULLNAME\fR
.RS 4
Updated full name
.RE
.PP
\fB\-\-password=\fR\fIPASSWORD\fR
.RS 4
Updated plain text password\&. Will prompt if no arg specified
.RE
.SH "FILES"
.sp
\fB~/\&.juicer\&.conf\fR \(em Juicer configuration file
.sp
\fB~/\&.juicer\-carts/\fR \(em Cart storage location
.SH "AUTHOR"
.sp
Juicer was written by GCA\-PC, Red Hat, Inc\&.\&.
.sp
This man page was written by Tim Bielawa <tbielawa@redhat\&.com> and Andrew Butcher <abutcher@redhat\&.com>\&.
.SH "COPYRIGHT"
.sp
Copyright \(co 2012, Red Hat, Inc\&.\&.
.sp
Juicer is released under the terms of the GPLv3+ License\&.
.SH "SEE ALSO"
.sp
\fBjuicer\fR(1), \fBjuicer\&.conf\fR(5)
.sp
\fBPulp User Documentation\fR \(em https://pulp\-user\-guide\&.readthedocs\&.org/en/pulp\-2\&.0/
.sp
The Juicer Homepage: https://github\&.com/juicer/juicer/
