'\" t
.\"     Title: juicer-admin
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/25/2012
.\"    Manual: Pulp repos and release carts
.\"    Source: Juicer 0.0.1
.\"  Language: English
.\"
.TH "JUICER\-ADMIN" "1" "06/25/2012" "Juicer 0\&.0\&.1" "Pulp repos and release carts"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
juicer \- create, edit, update, and publish release carts
.SH "SYNOPSIS"
.sp
juicer sub\-command [OPTIONS \&...] [PARAMETERS \&...]
.SH "DESCRIPTION"
.sp
Create, edit, update, and publish release carts\&.
.SH "CREATE"
.sp
juicer create CARTNAME \-r REPONAME item1 [ item2, [ \&...]]
.sp
Create a cart with the items specified\&.
.PP
\fBCARTNAME\fR
.RS 4
The name of the new release cart\&.
.RE
.PP
\fBITEMS\fR
.RS 4
Items to add to the cart\&.
.RE
.PP
\fB\-r\fR \fIREPONAME\fR
.RS 4
Install a group of
\fIITEMS\fR
into
\fIREPONAME\fR\&.
.RE
.SH "EDIT"
.sp
juicer edit CARTNAME
.sp
Interactively edit a release cart\&.
.PP
\fBCARTNAME\fR
.RS 4
The name of your release cart\&.
.RE
.SH "SHOW"
.sp
juicer show CARTNAME
.sp
Print the contents of a cart\&.
.PP
\fBCARTNAME\fR
.RS 4
The release cart to show\&.
.RE
.SH "UPDATE"
.sp
juicer update CARTNAME item1 [ item2 [ \&... ] ]
.sp
Update a release cart with items\&.
.PP
\fBCARTNAME\fR
.RS 4
The name of the release cart to update\&.
.RE
.PP
\fBITEMS\fR
.RS 4
The items to update in the cart\&.
.RE
.SH "CREATE-LIKE"
.sp
juicer create\-list CARTNAME OLDCARTNAME item1 [ item2 [ \&...] ]
.sp
Create a new cart based off an existing one\&.
.PP
\fBCARTNAME\fR
.RS 4
The name of your new release cart\&.
.RE
.PP
\fBOLDCARTNAME\fR
.RS 4
Cart to copy from\&.
.RE
.PP
\fBITEMS\fR
.RS 4
Items to update in the cart\&.
.RE
.SH "PUBLISH"
.sp
juicer publish CARTNAME
.sp
Publishes/Updates a cart on the pulp server\&.
.PP
\fBCARTNAME\fR
.RS 4
The name of the cart to publish\&.
.RE
.SH "CART-SEARCH"
.sp
juicer cart\-search CARTNAME
.sp
Search for a cart in pulp\&.
.PP
\fBCARTNAME\fR
.RS 4
The name of the cart to search for\&.
.RE
.SH "RPM-SEARCH"
.sp
juicer rpm\-search [\-r REPO [\&...]] [\-\-in ENVIRONMENT [\&...]]
.sp
Search for an RPM in pulp
.PP
\fB\-r\fR \fIrepos\fR [\fIrepos\fR \&...]
.RS 4
The repo(s) to limit search scope to\&.
.RE
.PP
\fB\-\-in\fR \fIenvironment\fR [\fIenvironment\fR \&...]
.RS 4
The environments to limit search scope to\&.
.RE
.SH "PARAMETERS FORMAT"
.sp
.if n \{\
.RS 4
.\}
.nf
Items given may be any number and combination of the following
input resource types:
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
http[s]://rpms/directory/ | http[s]://website/some\-thing\&.rpm
    URL to an HTTP directory index or an RPM\&. RPM paths are parsed
    from the index and then sent to the pulp server to be
    downloaded\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\&./directory/of/items | \&./path/to/item\&.rpm
    The items given are directly uploaded to the pulp server\&.
.fi
.if n \{\
.RE
.\}
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
Create and publish cart CRQ1337:
  $ %(prog)s create CRQ1337 \-r ruby http://file\&.derp/~smunilla/crq1337/ \e\e
      \-r services \&./new\-services\-rpms \e\e
      \-r candlepin /var/lib/mock/epel\-6\-x86_64/result/candlepin\&.el6\&.rpm
  Created new cart, CRQ1337\&.
  $ %(prog)s publish CRQ1337
  Cart published at http://juicer\&.util\&.phx1\&.redhat\&.com/carts/CRQ1337
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Update the existing cart, CRQ1337
  $ %(prog)s update CRQ1337 http://loki01:9001/builders/master\-candlepin/builds/0
  Updated xyz items in CRQ1337\&.
  $ %(prog)s publish CRQ1337
  Cart published at http://juicer\&.util\&.phx1\&.redhat\&.com/carts/CRQ1337
.fi
.if n \{\
.RE
.\}
.SH "FILES"
.sp
~/\&.juicer\&.conf \(em Juicer configuration file
.SH "AUTHOR"
.sp
Juicer was written by GCA\-PC, Red Hat, Inc\&.\&. This man page was written by Tim Bielawa <tbielawa@redhat\&.com\&.
.SH "COPYRIGHT"
.sp
Copyright \(co 2012, Red Hat, Inc\&.\&.
.sp
Juicer is released under the terms of the GPLv3+ License\&.
.SH "SEE ALSO"
.sp
\fBjuicer\-admin\fR(1), \fBjuicer\&.conf\fR(5)
